### PR TITLE
Feature/nim 1

### PR DESCRIPTION
**Pull request by nimdraks**

### CODE REVIEW

**Comment by nimdraks** [comment]
dddd

**Comment by nimdraks** [comment]
LGTM

**Comment by platinummonkey** [comment]
now I'm curious @nimdraks :D

**Comment by nimdraks** [comment]
@platinummonkey Thanks ;) Could I a you some questions?

**Comment by platinummonkey** [comment]
go for it!

**Comment by nimdraks** [comment]
@platinummonkey Thanks. Could you explain why OnSample() is not used at OnDropped() int [default.go](https://github.com/platinummonkey/go-concurrency-limits/blob/ff927e9381beaa602bad4999c2972a0a2576d152/limiter/default.go#L97)?

I know it is used at OnDropped in [Java code](https://github.com/Netflix/concurrency-limits/blob/3e697ef459107f3f54fa7d46abd5ca68a27f6626/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limiter/AbstractLimiter.java#L112)

**Pull request closed without merging**
