### PR TITLE
clear rttNoLoad when shouldProbe

### PR DESCRIPTION
**Pull request by mingkhuang**

### CODE REVIEW

**Review by platinummonkey — COMMENTED** [review]
Thanks! Was there a specific test we should add to validate this doesn't regress in the future?

**Comment by mingkhuang** [comment]
I don't have such a test yet. The issue is noticed by comparing the code of Java version and the code of Golang version. Maybe it is suitable to add a test that onsample a small rt and several common rt, wait for a while, onsample a larger rt, and test the minrt.

**Comment by platinummonkey** [comment]
ah https://github.com/Netflix/concurrency-limits/blob/master/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/VegasLimit.java#L200-L221

on L238 should we do the same then?

**Comment by mingkhuang** [comment]
Yes, L200-L221 is the corresponding code. L208 (rtt_noload = rtt) clears the old rtt_noload. This patch comes from L208. Why you mention L238?

**Comment by platinummonkey** [comment]
https://github.com/Netflix/concurrency-limits/blob/master/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/VegasLimit.java#L214 does the same thing it seems, so 2 bugs here

**Comment by mingkhuang** [comment]
I think L214 is not the same. It is guarded by "rtt < rtt_noload", so only smaller rrt is set to rrt_noload. It is the same as l.rttNoLoad.Add(float64(rtt)), for l.rttNoLoad is MinimumMeasurement.
L208 sets rrt_noload to rrt even if rrt >= rrt_noload, so the behavior is not the same as l.rttNoLoad.Add(float64(rtt)).

**Review by platinummonkey — APPROVED** [review]
got it, Thank you! 🙇

**Pull request merged**
